
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "/home/jorge/Documents/clion-2024.2.2/bin/cmake/linux/x64/share/cmake-3.29/Modules/CMakeDetermineSystem.cmake:205 (message)"
      - "CMakeLists.txt:16 (project)"
    message: |
      The system is: Linux - 6.8.0-45-generic - x86_64
...
